version: '2'
services:
  main:
    container_name: runner
    image: intelsdi/snap:alpine_test
    environment:
      - SNAP_VERSION=latest
    volumes:
      - ${PLUGIN_SRC}:/snap-plugin-collector-elasticsearch
    links:
      - elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - "9200" 
      - "9300"
