:global:
  build:
    matrix:
      - GOOS: linux
        GOARCH: amd64
      - GOOS: darwin
        GOARCH: amd64
.travis.yml:
  sudo: true
  services:
    - docker
  env:
    global:
      - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
      - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    matrix:
      - TEST_TYPE=small
      - TEST_TYPE=medium
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: m3CvvOZm2hUPSiWg7PKnJ+3Vm7Zg5g07KIjoB4hsYUv8FMFjnXlLTK3oYKTd4VcjdCgD6nMyQ9Propo+Tat4cbo9gnxQbk4gozD0ZeviAkxKG8OK3hjKlyqtzP9B+Yn1rHinpJBK1yOTj7CfFXpOfjfJHCeYfOQRsQi9wthW/w5fNc9KhjEMTcARa9Y1h5yWPExBVHvjV29GTmowxVIg8UTM3pD7GcaKv5f9mflIQq2Q9spmVn/Ary9y3vNS9VR06ypp/3pMH/6DzZfHNfv5wuXabjDj/q4SfCtsMmJiGT8FSYejdLDiG9cpQRr1+7YJsYS1UKx9OoaNhqvXX5el7Iqu84gBV8vor+V+VML0dR9KEcyxU57CTwBhkLghTtdLoy4UZSOL9IWDIIJNq5BBeXC0FYvyq3FdrFQT3xVqROpIMAeis7hpugr9M4WmtOIEW39IWUnsL2lgz2PGtzd/FKenlQ/LgZvrLJmLF/CZivqWAYDhAuV9w8nudGxVDihKD53JCR0yhuzZz8/kIr1JIN1kiIXq7Wx51hUpKSmhBTDmnPs2bu0at1BwL9khZgZuGbwUnuiqSIErqjXpOOxdyHvupoy/Y3lDOs11fCgoypQidwgCqNe4kK+LIuGmHpGHSvmFCcmXhSa/Qzu/+QIxCbIFH7jF6S11o0kteRixXVM=
    api_key:
      secure: ZJzXfB8D+vsexFFJ8t4nM0i9xJr/5+2G7oR/3iGMSYG5Iv88lEJM+MN44EbvgqAuF6Go9yExiKmWsJQ9SZKAAt0cNF1QZvuYPFXcWp1go+7ZncjSovfqSEA+BPoJwzkV+4ABNEmO9Y3IiayNWbMxbh1o3YmuqH4ndzu3p3TA83UndyyHSHT+O7wU4s+p+pHe6e18HRgcUfZIoLkeyExBxA+EWdp3QkBny8GyTzhogBGClveOuCt5A6aM0VeOFQkKR33NUnM48FTlbDuqwRs8bRlWxeD0z3rmymBqm/EoeV72ap6W9wsdIQHR308UVF9VehngZSjBwMEraL+VIplO2F08k0kBtNrW2KbLh3yP67hsT9jxKBQGCSIo19VoI1wTqYEf6cJzV9VYHU1njZ2uCb1psEXRXrJP3P8r6akRf7OqyShD2RvKQrnaKFFq88m5L5JKJ0vzbLhGHkeB5UG8iXWtyFqlyOmcz1Z0d7rU9ZZiNWNfemLebjd+Q5cCk9A8u+quysBIatiw5nGUX3c3DOD9GpJTkkSa7/ORj++F2CobLDXxBDlTbuW6wIlbHA2FnRBcOWSjV7OZocT7fMFYUzycDKrp3PmbgJkMBPQC0oBTn1WHnV5Mmiq7HAsQbRRyAdOBSvbzd6Qz5I3rpJlLVmeYtB6E8t4P1GPx/JOFt3Q=
